name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pytorch-cpu
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - deap
  - ipycanvas
